import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/Menu";
import Apps from "@/components/Apps";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative`}
      >
        <div className=" root relative h-full">
          <Menu />
          <Apps />
          {children}
        </div>
      </body>
    </html>
  );
}
